[build]
  command = "ng build --configuration production"
  publish = "dist/frontend/browser"
  ignore = "@netlify/angular-runtime"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    ssr = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200