services:
  - type: web
    name: runner-frontend
    env: static
    buildCommand: npm run build -- --configuration production
    staticPublishPath: dist/frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html